#Configuration file for deploying an appsody project

#For more information, see: https://github.com/appsody/appsody-operator/blob/master/doc/user-guide.md

apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata: 
  name: APPSODY_PROJECT_NAME
  labels:
    app: APPSODY_PROJECT_NAME
spec:
  version: 1.0.0
  applicationImage: APPSODY_DOCKER_IMAGE
  replicas: 1
  resources:
    limits:
      cpu: '2'
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 256Mi
  env:
    - name: LICENSE
      value: accept
    - name: ACE_SERVER_NAME
      value: {{.stack.serverName}}
    - name: ACE_TRUSTSTORE_PASSWORD
      value: truststorepwd
    - name: ACE_KEYSTORE_PASSWORD
      value: keystorepwd
    - name: LOG_FORMAT
      value: basic
    - name: ACE_ENABLE_METRICS
      value: 'true'
    - name: USE_QMGR
      value: {{.stack.useMQ}}
  stack: APPSODY_STACK
  securityContext:
    runAsUser: 1000
  service:
    type: NodePort
    port: 7800
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '9483'
  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /
      port: 7600
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /
      port: 7600
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
