FROM ibmcom/ace:{{.stack.aceVersion}}-amd64

USER aceuser

ENV APPSODY_PROJECT_DIR=/home/aceuser
ENV APPSODY_MOUNTS=/workspace/BARfiles:/home/aceuser/bars;/initial-config:/home/aceuser/initial-config
ENV APPSODY_WATCH_DIR=/home/aceuser/bars
ENV APPSODY_WATCH_IGNORE_DIR= 
ENV APPSODY_WATCH_REGEX="^.*.bar$"

# Optional command executed before RUN/TEST/DEBUG - typically used to install any dependencies from
ENV APPSODY_PREP=

ENV APPSODY_RUN="ace_compile_bars.sh && runaceserver"
ENV APPSODY_RUN_ON_CHANGE="/home/aceuser/deploy-bars.sh"
ENV APPSODY_RUN_KILL=false

#ENV APPSODY_DEBUG="echo -n \"Debugging \"; /bin/bash /project/userapp/hello.sh"
#ENV APPSODY_DEBUG_ON_CHANGE=$APPSODY_DEBUG
#ENV APPSODY_DEBUG_KILL=false

#ENV APPSODY_TEST="/bin/bash /project/userapp/tests/test.sh"
#ENV APPSODY_TEST_ON_CHANGE=$APPSODY_TEST
#ENV APPSODY_TEST_KILL=false

COPY ./LICENSE /home/aceuser/
COPY ./project/Dockerfile /home/aceuser/
ADD ./config/app-deploy.yaml /config/
COPY ./project/deploy-bars.sh /home/aceuser/

ENV LICENSE=accept
ENV ACE_SERVER_NAME=ACE_SERVER
ENV ACE_TRUSTSTORE_PASSWORD=truststorepwd
ENV ACE_KEYSTORE_PASSWORD=keystorepwd
ENV LOG_FORMAT=basic
ENV ACE_ENABLE_METRICS=true
ENV USE_QMGR={{.stack.useMQ}}

EXPOSE 9483 7600 7800 7843 9999

WORKDIR /home/aceuser/
